apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker
spec:
  selector:
    matchLabels:
      app: worker
  replicas: 12
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: gcr.io/zeebe-io/worker:zeebe
        imagePullPolicy: Always
        env:
          - name: JAVA_OPTIONS
            value: >-
              -Dzeebe.client.requestTimeout=62000
              -Dapp.worker.capacity=120
              -Dapp.worker.pollingDelay=1ms
              -Dapp.worker.completionDelay=50ms
              -Dapp.brokerUrl=5f5a17bf-3b00-4c3e-a86a-91af48744761.zeebe.ultrawombat.com:443
              -Dapp.tls=true
              -Dzeebe.client.requestTimeout=62000
              -XX:+HeapDumpOnOutOfMemoryError
          - name: LOG_LEVEL
            value: "warn"
          - name: ZEEBE_ADDRESS
            value: "5f5a17bf-3b00-4c3e-a86a-91af48744761.zeebe.ultrawombat.com:443"
          - name: ZEEBE_CLIENT_ID
            value: "k866f-mJXD3NGQsi.oUKqIBx_YTf~cds"
          - name: ZEEBE_CLIENT_SECRET
            value: "swOs6Ivu8lh9e_BGJoQuRnYwivuVqND.VlOoB4JXCgarHP01AQsGNSxob7iByLWr"
          - name: ZEEBE_AUTHORIZATION_SERVER_URL
            value: "https://login.cloud.ultrawombat.com/oauth/token"


        resources:
          limits:
            cpu: 4
            memory: 2Gi
          requests:
            cpu: 1
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: zeebe
    app.kubernetes.io/instance: zell-mid-cluster
    app.kubernetes.io/name: zeebe-cluster
  name: worker
spec:
  clusterIP: None
  ports:
  - name: http
    port: 9600
    protocol: TCP
    targetPort: 9600
  publishNotReadyAddresses: true
  selector:
    app: worker
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
