apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: broker-config
    files: 
      - zeebe.cfg.toml
      - log4j2.xml
  - name: broker-scripts
    files:
      - init.sh

resources:
  - service.yml
  - statefulset.yml