[cluster]
partitionsCount = 25
replicationFactor = 1

[threads]
cpuThreadCount = 6
ioThreadCount = 6

[data]
# snapshotPeriod = "3m"
# maxSnapshots = "3"

[backpressure]
enabled = true

[gateway]
enable = true

[gateway.monitoring]
enabled = true

[gateway.threads]
managementThreads = 1

[monitoring]
enabled = true
