[cluster]
partitionsCount = 5
replicationFactor = 1

[threads]
cpuThreadCount = 6
ioThreadCount = 6

[data]
# snapshotPeriod = "3m"
# maxSnapshots = "3"

[backpressure]
enabled = true

[gateway]
enable = true

[monitoring]
enabled = true
