[cluster]
partitionsCount = 25
replicationFactor = 1

[threads]
cpuThreadCount = 6
ioThreadCount = 6

[gateway]
enable = true

[gateway.monitoring]
enabled = true

[gateway.threads]
managementThreads = 1

[monitoring]
enabled = true

[backpressure]
enabled = true
algorithm = "aimd"
useWindowed = false

[backpressure.aimd]
initialLimit = 10
maxLimit = 100
requestTimeout = "300ms"
backoffRatio = 0.8

