[cluster]
partitionsCount = 25
replicationFactor = 1

[threads]
cpuThreadCount = 6
ioThreadCount = 6

[gateway]
enable = true

[gateway.monitoring]
enabled = true

[gateway.threads]
managementThreads = 1

[monitoring]
enabled = true
