apiVersion: v1
kind: Service
metadata:
  name: broker
spec:
  clusterIP: None
  publishNotReadyAddresses: True
  ports:
    - port: 26500
      name: grpc
    - port: 9600
      name: monitoring
    - port: 26502
      name: cluster