apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-2
spec:
  replicas: 0
  template:
    spec:
      containers:
      - name: starter
        image: gcr.io/zeebe-io/worker:zeebe
        imagePullPolicy: Always
        env:
          - name: JAVA_OPTIONS
            value: >-
              -Dapp.brokerUrl=$(BROKER_SERVICE_NAME):26500
              -Dapp.worker.capacity=16
              -Dapp.worker.threads=16
              -Dapp.worker.completionDelay=100ms
              -Dapp.worker.pollingDelay=100ms
              -Dapp.worker.jobType=benchmark-task-2
        resources:
          limits:
            cpu: 8
            memory: 512Mi
          requests:
            cpu: 3
            memory: 128Mi
