---
# Source: zeebe-cluster/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "zell-joiner-zeebe"
  labels:
    app.kubernetes.io/name: zeebe-cluster
    app.kubernetes.io/instance: zell-joiner
    app: "zell-joiner-zeebe"
    app: zeebe
  annotations:   
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: zeebe-cluster
      app.kubernetes.io/instance: zell-joiner
      app: "zell-joiner-zeebe"
  serviceName: "zell-joiner-zeebe"
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app.kubernetes.io/name: zeebe-cluster
        app.kubernetes.io/instance: zell-joiner
        app: "zell-joiner-zeebe"
      annotations:   
    spec:
      initContainers:    
      containers:
      - name: zeebe-cluster
        image: "gcr.io/zeebe-io/zeebe:zell-joiner"
        imagePullPolicy: Always
        env:
        - name: ZEEBE_BROKER_CLUSTER_CLUSTERNAME
          value: zell-joiner-zeebe    
        - name: ZEEBE_LOG_LEVEL
          value: debug
        - name: ZEEBE_BROKER_CLUSTER_PARTITIONSCOUNT
          value: "1"
        - name: ZEEBE_BROKER_CLUSTER_CLUSTERSIZE
          value: "3"
        - name: ZEEBE_BROKER_CLUSTER_REPLICATIONFACTOR
          value: "3"
        - name: ZEEBE_BROKER_THREADS_CPUTHREADCOUNT
          value: "4"
        - name: ZEEBE_BROKER_THREADS_IOTHREADCOUNT
          value: "4"
        - name: ZEEBE_BROKER_GATEWAY_ENABLE
          value: "false"
        - name: ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_CLASSNAME
          value: "io.zeebe.exporter.ElasticsearchExporter"
        - name: ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_URL
          value: "http://elasticsearch-master:9200"
        - name: ZEEBE_BROKER_NETWORK_COMMANDAPI_PORT
          value: "26501"
        - name: ZEEBE_BROKER_NETWORK_INTERNALAPI_PORT
          value: "26502"
        - name: ZEEBE_BROKER_NETWORK_MONITORINGAPI_PORT
          value: "9600"         
        - name: K8S_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name              
        - name: JAVA_TOOL_OPTIONS
          value: "-XX:+UseParallelGC  -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:MaxRAMPercentage=25.0  -XX:GCTimeRatio=4  -XX:AdaptiveSizePolicyWeight=90 -XX:+PrintFlagsFinal -Xmx4g -Xms4g -XX:+ExitOnOutOfMemoryError -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/usr/local/zeebe/data -XX:ErrorFile=/usr/local/zeebe/data/zeebe_error%p.log\n"
        - name: ZEEBE_LOG_APPENDER
          value: Stackdriver
        - name: ZEEBE_BROKER_EXECUTION_METRICS_EXPORTER_ENABLED
          value: "true"
        - name: ATOMIX_LOG_LEVEL
          value: debug
        ports:
        - containerPort: 9600
          name: http
        - containerPort: 26501
          name: command
        - containerPort: 26502
          name: internal
        readinessProbe:
          httpGet:
            path: /ready
            port: 9600
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
            limits:
              cpu: 5
              memory: 12Gi
            requests:
              cpu: 5
              memory: 12Gi
        volumeMounts:
        - name: config
          mountPath: /usr/local/zeebe/config/application.yaml
          subPath: application.yaml
        - name: config
          mountPath: /usr/local/bin/startup.sh
          subPath: startup.sh
        - name: data
          mountPath: /usr/local/zeebe/data
        - name: exporters
          mountPath: /exporters
        securityContext:
          capabilities:
              add:
              - NET_ADMIN
      volumes:
      - name: config
        configMap:
          name: "zell-joiner-zeebe"
          defaultMode: 0744
      - name: exporters
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ReadWriteOnce]
      storageClassName: ssd
      resources:
        requests:
          storage: "128Gi"
