---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zeebe
  labels:
    app: zeebe
spec:
  serviceName: "zeebe"
  selector:
    matchLabels:
      app: zeebe
  replicas: 3
  podManagementPolicy: Parallel
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
       accessModes:
         - ReadWriteOnce
       storageClassName: ssd
       resources:
         requests:
           storage: 128Gi
  template:
    metadata:
      labels:
        app: zeebe
    spec:
      volumes:
      - name: configuration
        configMap:
          name: zeebe
          defaultMode: 0744
      containers:
      - name: zeebe
        image: gcr.io/zeebe-io/zeebe:zell-joiner
        imagePullPolicy: Always
        ports:
        - containerPort: 26500
          name: gateway
        - containerPort: 26501
          name: command
        - containerPort: 26502
          name: internal
        - containerPort: 9600
          name: monitoring
        env:
        - name: ZEEBE_BROKER_CLUSTER_CLUSTERNAME
          value: "zell-joiner-zeebe"
        - name: ZEEBE_LOG_LEVEL
          value: debug
        - name: ZEEBE_BROKER_CLUSTER_PARTITIONSCOUNT
          value: "1"
        - name: ZEEBE_BROKER_CLUSTER_CLUSTERSIZE
          value: "3"
        - name: ZEEBE_BROKER_CLUSTER_REPLICATIONFACTOR
          value: "3"
        - name: ZEEBE_BROKER_THREADS_CPUTHREADCOUNT
          value: "4"
        - name: ZEEBE_BROKER_THREADS_IOTHREADCOUNT
          value: "4"
        - name: ZEEBE_BROKER_GATEWAY_ENABLE
          value: "false"
        - name: ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_CLASSNAME
          value: "io.zeebe.exporter.ElasticsearchExporter"
        - name: ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_URL
          value: "http://elasticsearch-master:9200"
        - name: ZEEBE_BROKER_NETWORK_COMMANDAPI_PORT
          value: "26501"
        - name: ZEEBE_BROKER_NETWORK_INTERNALAPI_PORT
          value: "26502"
        - name: ZEEBE_BROKER_NETWORK_MONITORINGAPI_PORT
          value: "9600"         
        - name: K8S_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name              
        - name: JAVA_TOOL_OPTIONS
          value: "-XX:+UseParallelGC  -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:MaxRAMPercentage=25.0  -XX:GCTimeRatio=4  -XX:AdaptiveSizePolicyWeight=90 -XX:+PrintFlagsFinal -Xmx4g -Xms4g -XX:+ExitOnOutOfMemoryError -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/usr/local/zeebe/data -XX:ErrorFile=/usr/local/zeebe/data/zeebe_error%p.log\n"
        - name: ZEEBE_LOG_APPENDER
          value: Stackdriver
        - name: ZEEBE_BROKER_EXECUTION_METRICS_EXPORTER_ENABLED
          value: "true"
        - name: ATOMIX_LOG_LEVEL
          value: debug
        resources:
          limits:
            cpu: 5
            memory: 12Gi
          requests:
            cpu: 5
            memory: 12Gi
        volumeMounts:
          - name: data
            mountPath: /usr/local/zeebe/data
          - name: configuration
            mountPath: /usr/local/zeebe/conf/zeebe.cfg.toml
            subPath: zeebe.cfg.toml
        command:
          - "/bin/sh"
          - "-c"
          - "ZEEBE_HOST=$(hostname -f) ZEEBE_CONTACT_POINTS=$(for i in $(seq 0 $((ZEEBE_CLUSTER_SIZE-1))); do echo -n \"zeebe-$i.$(hostname -d):26502,\"; done) ZEEBE_NODE_ID=${HOSTNAME##*-} exec tini -- /usr/local/bin/startup.sh"
        # enable for profiling
        securityContext:
            capabilities:
                add: ["NET_ADMIN", "SYS_ADMIN"]
        readinessProbe:
          httpGet:
              path: /ready
              port: 9600
          initialDelaySeconds: 20
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: zeebe
  labels:
    app: zeebe
spec:
  clusterIP: None
  publishNotReadyAddresses: True
  ports:
    - port: 26500
      name: grpc
    - port: 9600
      name: monitoring
  selector:
    app: zeebe
